name: food_delivery
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  custom_map_markers: ^0.0.2+1
  flutter:
    sdk: flutter
  flutter_easyloading: 3.0.5
  flutter_rating_bar: ^4.0.1
  get_it: 7.6.0
  google_maps_flutter: ^2.3.1
  http: ^1.1.0
  image_picker: ^1.0.8
  intl: 0.19.0
  otp_pin_field: ^1.2.0+2
  shared_preferences: 2.5.3

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Regular.otf
        - asset: assets/font/Metropolis-Medium.otf
          weight: 500
        - asset: assets/font/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/font/Metropolis-Bold.otf
          weight: 700
        - asset: assets/font/Metropolis-ExtraBold.otf
          weight: 800
